### ISSUE TITLE
Use download links from API?

### ISSUE THREAD

**Issue by timwis** [DataSF/open-data-explorer#122]
Hey folks, I ran into an interesting issue a couple weeks ago: the CSV downloaded uses the "human readable" field names, spaces and all, rather than the machine/api names. So if you change the human readable names in order to make the DataLens page more readable, you break any integrations against the CSV.

Reaching out to Socrata support, they let me know that I could use the API with `.csv` as the extension because the ceiling of the `$limit` parameter was removed. So you can have `xxxx-xxxx.csv?$limit=9999999999` and get the whole dataset, and you'd get the machine name field names. I imagine this would be a good way to get `.json` and `.geojson` as well.

P.S. This is looking really awesome!!

**Comment by jasonlally** [comment]
@timwis I implemented changes and things seem to work. I dropped support for xls/xlsx as CSV should be sufficient (better even) for users.
