### ISSUE TITLE
Finishing cosmetic updates for release 1.0.0-alpha.0

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#133]
The banner should have a link to a page that describes briefly what we mean by ALPHA and invites feedback.

**Comment by jasonlally** [comment]
@j9recurses - per our whiteboarding session here are the several things that should be done for our cosmetic changes - the PR will be against the release branch release/1.0.0-alpha.0

- [ ] Drop home and contact link
- [ ] Link help to support.datasf.org
- [ ] Add about page with some basic description of the project
- [ ] Change the color of the download links/API docs link
- [ ] Change button label API -> API Docs
- [ ] Add "alpha" bar at the top of the site (persistent) that includes link to about and google feedback form (create simple feedback form as well to link to)

**Comment by jasonlally** [comment]
@j9recurses here's a link to an empty form:

https://docs.google.com/forms/d/e/1FAIpQLSfrtwGrrGkGs0B_kkWhNJD3RyJRqCrjkpP8oikRQGr7nYjMdA/viewform

**Comment by j9recurses** [comment]
this is done. Will style the about page on the master branch
