### ISSUE TITLE
When summing, make chart title clearer

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#151]
If you sum a chart by another field, only the legend updates to indicate that the values are sums. The chart title should change as well so that instead of:

Projects by Project Status

Sum of Affordable Units by Project Status

**Comment by j9recurses** [comment]
This is done:
See screenshot for proof
<img width="1280" alt="screen shot 2017-01-25 at 2 37 44 pm" src="https://cloud.githubusercontent.com/assets/6549842/22312236/e233815a-e30b-11e6-9de0-cc2b0e2218b2.png">

**Comment by j9recurses** [comment]
The axis should read "Sum Of 3bd Units By Family Units"

<img width="1280" alt="screen shot 2017-01-27 at 2 22 15 pm" src="https://cloud.githubusercontent.com/assets/6549842/22389772/348f8cb4-e49c-11e6-8368-559135cd5bec.png">
