### ISSUE TITLE
Investigate reason for different widths on different machines

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#152]

**Comment by j9recurses** [comment]
This is fixed. There was a bug in the code that caused this. 

Example of fix
<img width="1280" alt="screen shot 2016-12-06 at 3 14 11 pm" src="https://cloud.githubusercontent.com/assets/6549842/20948132/53a95a60-bbc7-11e6-81d3-62f64754e134.png">

**Comment by j9recurses** [comment]
Bug specifically was that the function getting the the wXh had a logical error
