### ISSUE TITLE
Resize download and API buttons to render based on H XW of browswer window

### ISSUE THREAD

**Issue by j9recurses** [DataSF/open-data-explorer#153]
<img width="1280" alt="screen shot 2016-10-25 at 4 23 26 pm" src="https://cloud.githubusercontent.com/assets/6549842/19707876/5f7a5a9c-9acf-11e6-9ffd-07ff386da50e.png">

These buttons should be all on one row.

**Comment by jasonlally** [comment]
We should probably just use media queries to accomplish this, rather than detecting height and width with javascript.

**Comment by jasonlally** [comment]
Closed by #222
