### ISSUE TITLE
Cast undefined as "Blank"

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#156]
When a category is not defined, Socrata middleware will pass back:

{ value: 1000 } with no label

![screen shot 2016-12-05 at 11 10 51 am](https://cloud.githubusercontent.com/assets/534176/20898520/8334d90e-badb-11e6-9fc5-f1203479729e.png)

**Comment by j9recurses** [comment]
this is done:

<img width="1280" alt="screen shot 2016-12-05 at 4 15 41 pm" src="https://cloud.githubusercontent.com/assets/6549842/20908072/01f3afec-bb07-11e6-878e-a1f0044b599f.png">
