### ISSUE TITLE
Adjust numeric labeling to include decimals in millions

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#173]
http://localhost:8000/#/public-safety/fire-department-calls-for-service/nuek-vuh3/chart_experimental?_k=dhxgvx

2M shows up twice in the chart below:

![screen shot 2016-10-26 at 9 08 20 am](https://cloud.githubusercontent.com/assets/534176/19734277/cd9d946c-9b5b-11e6-9c37-a766b47792b2.png)

**Comment by j9recurses** [comment]
This is fixed now. 
I changed this: 
 let formatValue = d3.format('.1s')
to this:
 let formatValue = d3.format('.3s')
Basically, what happening is here that I'm passing a formatting function to the axis labeling component. 
Originally, I set the format to only go to 1 decimal place. 
Hence, something like 2.2 million, with only 1 decimal place would render to 2M
So, if I add 3 decimals places, the function will format something like 2.25 million to 2.25M. 
Here is what the browser shows now after the fix: 
<img width="1280" alt="screen shot 2016-12-05 at 4 46 22 pm" src="https://cloud.githubusercontent.com/assets/6549842/20908518/602c6510-bb0a-11e6-82f1-79e05e4cdd7d.png">
