### ISSUE TITLE
Fix Y max value on chart layout

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#192]
The max y value for the chart appears to be set based on the total of all columns as opposed to based on the max column.  This creates excessive headroom on the charts.

Here's an example:

![screen shot 2016-12-05 at 10 04 18 am](https://cloud.githubusercontent.com/assets/534176/20896406/72cffebc-bad2-11e6-9b1f-1bc9db90cfcf.png)

**Comment by j9recurses** [comment]
This is fixed.

Recharts accepts parameters for the domain of the x and y axis.

In the code, I arbitrarily padded the domain with value of 100 like this:
domain={[0, 'dataMax + 100']}

Now, I am proportionally padding the domain of the numeric axis like this:
let maxValue = findMaxObjKeyValue(chartData, 'value')
//above finds the max value in the chartDataObject

 let domainMax = maxValue + (maxValue * 0.03)
//take the max value and add 3%.

At this point, we can pass the domainMax variable to the recharts domain parameter for the axis component, like this:
domain={[0, domainMax]}

Let me know if you want me to add more than a 3% padding to max value for the axis....
