### ISSUE TITLE
Prevent numeric data fields from being rendered not as histograms

### ISSUE THREAD

**Issue by j9recurses** [DataSF/open-data-explorer#195]
This is part of larger user story of users being able to view numeric data as histograms..

Right now, we are rendering numeric columns as regular bar graphs which doesn't make sense. 

Need to clean this up. Here is an example
<img width="1280" alt="screen shot 2016-12-05 at 10 23 32 am" src="https://cloud.githubusercontent.com/assets/6549842/20897158/d0d00b1c-bad5-11e6-922f-e3ddd3562a12.png">

**Comment by j9recurses** [comment]
example of this is [here]: (http://localhost:8000/#/housing-and-buildings/mayor-s-office-of-housing-and-community-development-affordable-rental-portfolio/9rdx-httc/chart_experimental?_k=q9g7n2)

**Comment by jasonlally** [comment]
Addressed by #204
