### ISSUE TITLE
On bar charts with year/date data, need to sort bar values by year

### ISSUE THREAD

**Issue by j9recurses** [DataSF/open-data-explorer#197]
Example of this bug: 

<img width="1280" alt="screen shot 2016-12-05 at 11 43 06 am" src="https://cloud.githubusercontent.com/assets/6549842/20899657/22ed64bc-bae0-11e6-9e8e-73c133e37ab0.png">

**Comment by j9recurses** [comment]
actually, on closer look- these values for years are sorted. I'm adding this issue to the icebox for now;
more of design question than a bug.

With more than 10 years, the bar charts automatically flips it so the categories are on the Y axis. 
This creates a somewhat confusion experience for users....

**Comment by j9recurses** [comment]
This is fixed; Jason and I decieded that date column bar graphs should only have a horizontal layout. 

<img width="1280" alt="screen shot 2017-01-25 at 10 07 53 am" src="https://cloud.githubusercontent.com/assets/6549842/22303054/5f1df91e-e2e6-11e6-97ba-945520366e44.png">

**Comment by jbonaguro** [comment]
good choice!


---------------------------------------------------------
Joy Bonaguro
Chief Data Officer
Office of Mayor Edwin M. Lee
City and County of San Francisco
@datasf | DataSF<http://datasf.org/> | SF Open Data<https://data.sfgov.org/>
________________________________
