### ISSUE TITLE
When a numeric column is all zeroes, histogram chart type won't display

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#205]
For example: http://localhost:8000/#/housing-and-buildings/affordable-housing-pipeline/aaxw-2cb8/chart_experimental?_k=mzgq9x

Here's the data the query returns: `[{"label":"0","value":"129"}]`

**Comment by j9recurses** [comment]
Looked at this in more detail-I handled this in the middleware.
Chart (older version) is expecting an array of [ ['x', '0', 1] ['count of col', 2, 3]
However, when there is a column of zeros, it throws a data error.
In Socrata.js I added a check to see if json only contains 1 value of zero. ie:
[ {'label':0, 'value': 20}]
And then just create an array that chart is expecting to get around this error. 

Here is what now shows up when chart is zero:
<img width="1280" alt="screen shot 2016-12-09 at 12 25 00 pm" src="https://cloud.githubusercontent.com/assets/6549842/21063658/a7dccc5c-be0b-11e6-8ef1-639dcd984c93.png">
