### ISSUE TITLE
Dates not displaying correctly on timeseries chart by year

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#209]
See:  http://datasf-explorer.tk/#/public-safety/sfpd-incidents-from-1-january-2003/tmnf-yvry/chart_experimental?q=%7B%22selectedColumn%22%3A%22date%22%7D

Years are off by 1 year. 2002 should be 2003, 2016 should be 2017.

![screen shot 2017-01-22 at 10 47 02 pm](https://cloud.githubusercontent.com/assets/534176/22194055/bdfeb11a-e0f4-11e6-952d-fdeeb151874d.png)

**Comment by j9recurses** [comment]
This is fixed. January starts at 0 in javascript! Learn something every day!

<img width="1280" alt="screen shot 2017-01-24 at 5 04 35 pm" src="https://cloud.githubusercontent.com/assets/6549842/22273765/4b42a19a-e257-11e6-99c7-d820fbd55866.png">
