### ISSUE TITLE
Small numbers on y-axis formatted incorrectly

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#265]
Looks like anything below 1 gets formatted as millions.

![screen shot 2017-03-01 at 4 29 15 pm](https://cloud.githubusercontent.com/assets/534176/23487653/5686690e-fe9c-11e6-9b50-8e2ef8b208a3.png)

Example:
http://localhost:8000/#/housing-and-buildings/eviction-notices/5cei-gny5/charts?q=%7B%22selectedColumn%22%3A%22file_date%22%2C%22filters%22%3A%7B%22checkboxes%22%3A%7B%22key%22%3A%22checkboxes%22%2C%22options%22%3A%7B%22selected%22%3A%5B%22non_payment%22%2C%22breach%22%5D%2C%22filterType%22%3A%22booleanCategory%22%2C%22join%22%3A%22and%22%7D%7D%7D%2C%22dateBy%22%3A%22month%22%7D

**Comment by j9recurses** [comment]
this is fixed:
<img width="1280" alt="screen shot 2017-03-02 at 3 10 01 pm" src="https://cloud.githubusercontent.com/assets/6549842/23531242/660fc186-ff5a-11e6-8d3e-c586b6b115f1.png">
