### ISSUE TITLE
Invalid array length error thrown on certain histogram charts

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#270]
Example: Affordable Housing Pipeline -> % Affordable field

Returns data, but throws error

```json
[{"label":"0","value":"51"}
,{"label":"0.02","value":"1"}
,{"label":"0.05","value":"2"}
,{"label":"0.08","value":"2"}
,{"label":"0.09","value":"3"}
,{"label":"0.1","value":"10"}
,{"label":"0.11","value":"13"}
,{"label":"0.12","value":"28"}
,{"label":"0.13","value":"15"}
,{"label":"0.14","value":"11"}
,{"label":"0.15","value":"18"}
,{"label":"0.16","value":"6"}
,{"label":"0.17","value":"2"}
,{"label":"0.2","value":"8"}
,{"label":"0.21","value":"3"}
,{"label":"0.25","value":"1"}
,{"label":"0.28","value":"1"}
,{"label":"0.39","value":"1"}
,{"label":"0.4","value":"2"}
,{"label":"0.94","value":"1"}
,{"label":"0.96","value":"1"}
,{"label":"0.97","value":"3"}
,{"label":"0.98","value":"15"}
,{"label":"0.99","value":"71"}
,{"label":"1","value":"48"}]
```

![screen shot 2017-03-02 at 2 36 21 pm](https://cloud.githubusercontent.com/assets/534176/23532696/a95b148e-ff61-11e6-89e8-8b20a43278f1.png)

**Comment by jasonlally** [comment]
This is no longer the case, fixed the error message, but now just not casting the data correctly for this same chart.

**Comment by j9recurses** [comment]
here what the bug looks like now:
<img width="1280" alt="screen shot 2017-03-03 at 9 35 48 am" src="https://cloud.githubusercontent.com/assets/6549842/23561833/d3e44282-fff4-11e6-8874-29bee93f811b.png">

**Comment by j9recurses** [comment]
this is fixed; there was a problem with axis scales:
<img width="1280" alt="screen shot 2017-03-03 at 9 55 15 am" src="https://cloud.githubusercontent.com/assets/6549842/23562518/9623bcd6-fff7-11e6-8b43-dedb673669aa.png">
