### ISSUE TITLE
Add group by boolean variables

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#28]

**Comment by j9recurses** [comment]
So this is the current state of group by with booleans:

<img width="1280" alt="screen shot 2016-12-05 at 9 49 29 am" src="https://cloud.githubusercontent.com/assets/6549842/20895886/34aaadb4-bad0-11e6-8d51-14ebf9f5cb5d.png">

**Comment by j9recurses** [comment]
he color slivers are too small to be usable....need to re-think how we can achieve this...

**Comment by j9recurses** [comment]
On second thought, boolean column types are covered by new charting library, so I'm closing this issue for now...seems more like a group by issue than a boolean data type issue...
