### ISSUE TITLE
Field metadata dataset not dropping no longer existing field names

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#287]
311 dataset was just changed over to a new schema, but the fields weren't dropped from the field dataset which results in the explorer trying to query fields that don't exist.

The field metadata scripts should use whatever is in Socrata as the canonical list to join additional information against.

http://localhost:8000/#/city-infrastructure/case-data-from-san-francisco-311-sf311/vw6y-z8j6/charts?_k=t5nns1

![screen shot 2017-04-23 at 11 46 42 am](https://cloud.githubusercontent.com/assets/534176/25316355/8dbf65c2-281a-11e7-9683-79ddea46f852.png)

**Comment by j9recurses** [comment]
This is fixed. This was a data problem further upstream;  [see this commit in the fetch metadata repo ](https://github.com/DataSF/fetch-metadata-fields/commit/0f64dc78cb177488f8c3427bc325d8b126457ece) for more details
<img width="1280" alt="screen shot 2017-05-29 at 12 05 15 pm" src="https://cloud.githubusercontent.com/assets/6549842/26559904/6f9b5ef2-4467-11e7-8c0f-5916d00aebc8.png">
