### ISSUE TITLE
Sort order bug when grouping a date/time dimension

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#288]
When selecting a group by option on date/time data, the sort is not in chronological order.

http://localhost:8000/#/public-safety/police-calls-for-service/hz9m-tj6z/charts?q=%7B%22selectedColumn%22%3A%22call_dttm%22%2C%22dateBy%22%3A%22month%22%2C%22groupBy%22%3A%22address_type%22%7D

![screen shot 2017-04-26 at 12 11 59 pm](https://cloud.githubusercontent.com/assets/534176/25452484/915a45b4-2a7a-11e7-917d-064b9dccf817.png)

**Comment by j9recurses** [comment]
This is fixed now for group by date columns. The fix involved two parts:
1.We needed to fill in values for missing years.
2. For each year/date period, we need to fill in the missing category for the group by, setting the value of the group to zero. 
3. After filling in the missing values, we sort the date objects 

See screenshots attached that verify the fix:
<img width="1280" alt="screen shot 2017-06-12 at 11 43 54 am" src="https://user-images.githubusercontent.com/6549842/27049694-ee3c44da-4f64-11e7-84f2-96736f902053.png">

<img width="1280" alt="screen shot 2017-06-12 at 11 44 23 am" src="https://user-images.githubusercontent.com/6549842/27049712-fd3e3da8-4f64-11e7-9fe4-c158ea3b74ca.png">
