### ISSUE TITLE
Deal with null years/dates in the display of timeseries charts

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#290]
## Expected behavior
For timeseries data, we should treat missing years as 0 and chart as such

## Current behavior

Currently the charts place data for each of the years and skip the missing ones. For line charts the points are then interpolated making it appear like data exist for all years at a glance.

Image below shows a line chart with 2009 and no 2010 or 2011, the next year is 2012. The line connects 2009 directly to 2012.

![screen shot 2017-04-27 at 12 41 06 pm 1](https://cloud.githubusercontent.com/assets/534176/25501315/2861241a-2b47-11e7-95a8-b2de6ee435ac.png)

Same data on a bar chart
![screen shot 2017-04-27 at 12 47 43 pm](https://cloud.githubusercontent.com/assets/534176/25501542/f1c75f5e-2b47-11e7-81bd-153509762c61.png)

## Steps to reproduce

Go to: http://localhost:8000/#/housing-and-buildings/affordable-housing-pipeline/aaxw-2cb8/charts?q=%7B%22selectedColumn%22%3A%22issuance_of_building_permit%22%7D

**Comment by j9recurses** [comment]
This is fixed.  I added the missing dates in the middleware in socrata.js. 
Here are the screenshots that show the final result:
For missing years:
<img width="1280" alt="screen shot 2017-05-29 at 1 56 29 pm" src="https://cloud.githubusercontent.com/assets/6549842/26561917/fe4c43a0-4476-11e7-9731-cd6c7bc14c2a.png">
For missing months:
<img width="1280" alt="screen shot 2017-05-29 at 1 56 39 pm" src="https://cloud.githubusercontent.com/assets/6549842/26561928/0f1b4514-4477-11e7-9a1a-82551e7ca440.png">
