### ISSUE TITLE
Change URL for app

### ISSUE THREAD

**Issue by j9recurses** [DataSF/open-data-explorer#308]
Possibly:

http://beta.explore.datasf.org
http://edge.explore.datasf.org

- [x] Jason configure DNS for datasf.org domain
- [x] Janine set up server

**Comment by jasonlally** [comment]
@j9recurses I've set up beta.explore.datasf.org and edge.explore.datasf.org to point at the server. I think you just have to create the nginix records to serve up the staging and production

production = beta.explore
staging = edge.explore

**Comment by jasonlally** [comment]
Yay, sites are now available at http://beta.explore.datasf.org and http://edge.explore.datasf.org

Beta is where we'll send people for the initial release. I kept the .tk domains as well for now, we'll need to swap in the new domains in the deploy scripts, but I didn't want to change too many things at once.
