### ISSUE TITLE
Reconfigure airbrake configuration

### ISSUE THREAD

**Issue by j9recurses** [DataSF/open-data-explorer#310]
Some things changed with Airbrake, need to look into updating configuraiton.

**Comment by jasonlally** [comment]
This is reconfigured mostly now @j9recurses can you make sure you're developing off of the latest develop branch, which will keep any errors during development out of airbrake.

There's one issue remaining where the server environment still isn't being tagged, but it's not a critical issue. Leaving this open for now.

**Comment by jasonlally** [comment]
Closed by #347
