### ISSUE TITLE
Sort order on Dataset Catalog needs to be revealed to user

### ISSUE THREAD

**Issue by j9recurses** [DataSF/open-data-explorer#323]
Datasets are sorted in a particular way, however, the way that the dataset cards are sorted aren't transparent to the user
<img width="1280" alt="screen shot 2017-06-21 at 4 44 57 pm" src="https://user-images.githubusercontent.com/6549842/27411214-2cbf4d90-56a1-11e7-93db-64024dd904b6.png">

**Comment by jasonlally** [comment]
For this, let's actually decide on a default sort order and then make that the case and report that. 

This requires some Algolia setup as it's using whatever defaults are in the system for ordering, so it's not actually anything that would be useful to the user. For simplicity's sake, we can start with alpha and then layer in others.

Sorting by relevancy and other factors will take some adjustments of the Algolia algorithm and feeding it the right data. It's not hard, but that could be broken into it's own issue and development and I'd put that in the next release.
