### ISSUE TITLE
Display number of rows in dataset on search page

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#337]
This change will take a bit of engineering to make sure the number of rows is in the algolia index. To keep things simple, we're currently syncing the asset inventory dataset, but that does not have number of rows.

I think the simplest thing to do is to add description to the dataset profiles dataset and use that in the index script.

For now we'll leave this out until that work can happen. It shouldn't delay release.

**Comment by j9recurses** [comment]
Duplicate
