### ISSUE TITLE
When grouping by a field and applying a single filter on that same field, bar chart breaks

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#357]
When a user applies a grouping and filters by a single field it's equivalent to just filtering on a single field without grouping. However, users want to interactively add and remove filters while grouping.

I was able to fix the issue with line charts, but bars are a bit trickier. I'm logging this here to revisit this later and work on something else. I think a more fool-proof way to deal with this issue is in the middleware. Essentially we can just treat grouped data with a single category as a one-dimensional chart. We could just pass down data so that it uses the appropriate component.

<img width="421" alt="screen shot 2017-08-02 at 9 33 50 am" src="https://user-images.githubusercontent.com/534176/28884189-bbd5489c-7765-11e7-8940-5a10cb7713a4.png">

<img width="1047" alt="screen shot 2017-08-02 at 9 33 33 am" src="https://user-images.githubusercontent.com/534176/28884195-c069e23c-7765-11e7-8bdb-8452feadee61.png">

**Comment by jasonlally** [comment]
Was able to fix this issue on line charts, but not bar charts. There may be a more comprehensive way to solve this which is at the middleware layer to essentially treat these types of groupings as basic charts and send data down in that format.

**Comment by j9recurses** [comment]
This working now. 

This handles the issue in two places: the middleware and right before the app renders a graph.
For all group by, 2 things now happen
1. The middle bar checks to see how many groupKeys there are- if only one group key exists, the middleware maps the data to the data structure of non-grouped data.
2. The chart canvas component checks to how many groupKeys there are- if only one group key exists, then, then isGroupBy gets set to false, causing the graph to be rendered as a standard, non grouped graph. 

Picture to show the final result:

<img width="1280" alt="screen shot 2017-08-10 at 4 42 54 pm" src="https://user-images.githubusercontent.com/6549842/29196701-fa5eae7e-7dea-11e7-9962-aee23fa0ed01.png">
