### ISSUE TITLE
Y-Axis not being re-calculated when switching between chart types

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#368]
When switching between grouped data chart types (e.g line -> bar) the y-axis isn't recalculated to accommodate the stacking.

Chart looks good as line
![screen shot 2017-08-02 at 11 53 58 am](https://user-images.githubusercontent.com/534176/28889600-5d0727d6-7779-11e7-9168-9b229d968db3.png)

But when stacking groups, y-axis isn't recalibrated to the new max
![screen shot 2017-08-02 at 11 54 07 am](https://user-images.githubusercontent.com/534176/28889611-6600478c-7779-11e7-8123-c79db1c55c98.png)
![screen shot 2017-08-02 at 11 54 18 am](https://user-images.githubusercontent.com/534176/28889612-6600575e-7779-11e7-9ccb-3373745cb9dc.png)

**Comment by j9recurses** [comment]
This is fixed:
<img width="1280" alt="screen shot 2017-08-10 at 2 57 24 pm" src="https://user-images.githubusercontent.com/6549842/29193941-472b126a-7ddc-11e7-9207-0febbe8d05d5.png">
<img width="1280" alt="screen shot 2017-08-10 at 2 57 32 pm" src="https://user-images.githubusercontent.com/6549842/29193948-4d50e96c-7ddc-11e7-9993-c0109a9ed1ed.png">

**Comment by j9recurses** [comment]
This is fixed

<img width="1280" alt="screen shot 2017-08-10 at 2 59 09 pm" src="https://user-images.githubusercontent.com/6549842/29194007-8ed1d1d0-7ddc-11e7-9bb3-db739b62e535.png">
<img width="1280" alt="screen shot 2017-08-10 at 2 59 15 pm" src="https://user-images.githubusercontent.com/6549842/29194011-92fbea52-7ddc-11e7-81ff-611b8a4878a9.png">
