### ISSUE TITLE
Investigate what’s causing line charts to draw in 2 pieces

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#373]
This is just a display bug, so it doesn't have to hold up first release, but would be good to understand the root cause.

**Comment by j9recurses** [comment]
This is fixed. 

I had tried to turn off the line animation because it seemed unnessary, using the isAnimationActive={false} prop.  (If set false, animation of line will be disabled.)  Obviously, this didn't work as expected, so I removed the  isAnimationActive and now everything is working.

**Comment by j9recurses** [comment]
This is also fixed for area charts

**Comment by j9recurses** [comment]
I upgraded the Recharts. After upgrade a different animation issue appeared where the line was moving horizontal out. For now, I've removed animations from line charts.
