### ISSUE TITLE
Blank (missing or null) values do not show on chart when grouping

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#374]
I think this is actually happening at the query level in the socrata middleware where labels = null are excluded when grouping.

I'll have to double check. This points to maybe a different feature which is actually to allow users to include or exclude these values.

**Comment by jasonlally** [comment]
Looks like this may be a little more embedded in how the data is being returned. For troubleshooting:

![screen shot 2017-08-06 at 7 00 23 pm 1](https://user-images.githubusercontent.com/534176/29009618-a9f9287e-7ad9-11e7-8857-652ed21e2865.png)

Notice there is a "blank" label and a blank key in the data, but the groupKeys returns undefined, may be as simple as adjusting the logic in the middleware that passes down the groupKeys.

<img width="905" alt="screen shot 2017-08-06 at 7 01 40 pm" src="https://user-images.githubusercontent.com/534176/29009626-b578248e-7ad9-11e7-9c32-5eee82a0563a.png">

**Comment by j9recurses** [comment]
I'm looking it into this- basically, for items with undefined keys, socrata doesn't return a label. I can correct this is the middle ware
<img width="1280" alt="screen shot 2017-08-10 at 4 48 24 pm" src="https://user-images.githubusercontent.com/6549842/29196823-e42a481a-7deb-11e7-9d75-715ebf9321e3.png">

**Comment by j9recurses** [comment]
This is fixed. If no label exists for an object returned from Socrata API, I return "Blank"
See screenshot attached, in the legend- you will see a blank label now. 

<img width="1280" alt="screen shot 2017-08-10 at 4 55 24 pm" src="https://user-images.githubusercontent.com/6549842/29196969-e1e94d5c-7dec-11e7-93b1-119572eedeeb.png">
