### ISSUE TITLE
Intermittent issue with the chart resizing itself

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#388]
This seems to happen when you iterate through a couple of charts. Haven't found a pattern yet, but basically, try building one chart and then switching to a different field in the field picker and you'll eventually get something like this:

<img width="1664" alt="screen shot 2017-08-10 at 11 41 58 am" src="https://user-images.githubusercontent.com/534176/29186865-93a78930-7dc2-11e7-8cd2-1801eb483843.png">

It'll then fix itself on the next query.

**Comment by j9recurses** [comment]
I wasn't able to reproduce this issue- I suspect that it may be related to #373....

Closing for now...
