### ISSUE TITLE
In appropriate chart types show up for numeric data

### ISSUE THREAD

**Issue by j9recurses** [DataSF/open-data-explorer#395]
The ability to select line, bar, and area chart types show up for  numeric data show up when the user selects a numeric field.  

See screenshot attached. 
<img width="1280" alt="screen shot 2017-08-16 at 3 26 21 pm" src="https://user-images.githubusercontent.com/6549842/29387990-9d7b1420-8297-11e7-85e9-27971df69e4f.png">

**Comment by jasonlally** [comment]
This is related to something else I'm working on in the branch, I can knock this out.
