### ISSUE TITLE
Field details api endpoint keeps timing out

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#404]
@j9recurses 

Failing intermittently. Seems to especially have an issue with police department incidents. Getting a 504 Gateway Timeout for
/api/v1/fielddetails/

**Comment by j9recurses** [comment]
I looked at this- I can't recreate the 504. 
I hit the endpoint a bunch in postman and I get nothing:
http://metadatasf.tk/api/v1/fielddetails/tmnf-yvry

**Comment by jasonlally** [comment]
So the 504 is thrown when a server fails to return talking to another server, so that indicates the timeout being between the metadata api and Socrata, meaning Socrata wasn't responding.

It looks fine for now, but what we can do is handle 504s in the app layer so that the user has a clear message that the server is currently unreachable.
